/**
 * Pinned intermediate values (TASKS R1 "Done when"): later physics tasks
 * assert against tests/fixtures/reference-values.json. This test proves the
 * pipeline still reproduces the pinned numbers exactly enough.
 */
import { existsSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { REFERENCE_VALUES_PATH, loadFixturePair } from '../../tests/support/fixtures';
import { ISS_NORAD_ID, runOurPipeline, fixtureObserver } from '../../tests/support/heavensAbove';
import { gmstRad, lookAnglesFrom, ommToSatrec, propagateEci, sunAltitudeDeg, sunVectorEqd } from './index';

interface Vec {
  x: number;
  y: number;
  z: number;
}
interface Reference {
  fixture: string;
  ommFixture: string;
  t: number;
  eci: { position: Vec; velocity: Vec };
  gmstRad: number;
  lookAngles: { azDeg: number; elDeg: number; rangeKm: number };
  sunAltitudeDeg: number;
  sunUnitVectorEqd: Vec;
  firstGoldenPass: {
    start: { t: number; azDeg: number; elDeg: number; rangeKm: number };
    peak: { t: number; azDeg: number; elDeg: number; rangeKm: number };
    end: { t: number; azDeg: number; elDeg: number; rangeKm: number };
    startReason: string;
    endReason: string;
    peakMagnitude: number;
    twilight: boolean;
  } | null;
}

const expectVec = (a: Vec, b: Vec, digits: number): void => {
  expect(a.x).toBeCloseTo(b.x, digits);
  expect(a.y).toBeCloseTo(b.y, digits);
  expect(a.z).toBeCloseTo(b.z, digits);
};

describe('reference-values.json', () => {
  it('exists (generated by `npx tsx scripts/validate-iss.ts --write-reference`)', () => {
    expect(existsSync(REFERENCE_VALUES_PATH), `missing ${REFERENCE_VALUES_PATH}`).toBe(true);
  });

  if (!existsSync(REFERENCE_VALUES_PATH)) return;
  const ref = JSON.parse(readFileSync(REFERENCE_VALUES_PATH, 'utf8')) as Reference;
  const pair = loadFixturePair(ref.fixture, ref.ommFixture);
  const iss = pair.omm.find((r) => r.NORAD_CAT_ID === ISS_NORAD_ID);
  const observer = fixtureObserver(pair.ha);

  it('reproduces the ISS ECI state, GMST, look angles, sun altitude and sun vector at capturedAt', () => {
    if (!iss) throw new Error('ISS missing from OMM fixture');
    const state = propagateEci(ommToSatrec(iss), ref.t);
    if (!state) throw new Error('propagation failed');
    expectVec(state.position, ref.eci.position, 6);
    expectVec(state.velocity, ref.eci.velocity, 9);
    expect(gmstRad(ref.t)).toBeCloseTo(ref.gmstRad, 12);
    const look = lookAnglesFrom(observer, state.position, ref.t);
    expect(look.azDeg).toBeCloseTo(ref.lookAngles.azDeg, 6);
    expect(look.elDeg).toBeCloseTo(ref.lookAngles.elDeg, 6);
    expect(look.rangeKm).toBeCloseTo(ref.lookAngles.rangeKm, 6);
    expect(sunAltitudeDeg(observer, ref.t)).toBeCloseTo(ref.sunAltitudeDeg, 6);
    expectVec(sunVectorEqd(ref.t), ref.sunUnitVectorEqd, 9);
  });

  it('reproduces the first golden pass start / peak / end', () => {
    const first = runOurPipeline(pair.ha, pair.omm)[0];
    if (!ref.firstGoldenPass) {
      expect(first).toBeUndefined();
      return;
    }
    expect(first).toBeDefined();
    if (!first) return;
    for (const key of ['start', 'peak', 'end'] as const) {
      expect(first[key].t).toBe(ref.firstGoldenPass[key].t);
      expect(first[key].azDeg).toBeCloseTo(ref.firstGoldenPass[key].azDeg, 6);
      expect(first[key].elDeg).toBeCloseTo(ref.firstGoldenPass[key].elDeg, 6);
      expect(first[key].rangeKm).toBeCloseTo(ref.firstGoldenPass[key].rangeKm, 6);
    }
    expect(first.startReason).toBe(ref.firstGoldenPass.startReason);
    expect(first.endReason).toBe(ref.firstGoldenPass.endReason);
    expect(first.peakMagnitude).toBeCloseTo(ref.firstGoldenPass.peakMagnitude, 6);
    expect(first.twilight).toBe(ref.firstGoldenPass.twilight);
  });
});
