/**
 * Pinned intermediate values (TASKS R1 "Done when", H): the end-to-end pin.
 * Each module's own test asserts its slice of `reference-values.json`; this
 * file proves the whole pipeline still lands on the pinned first golden pass
 * and that the file itself exists and names a committed fixture.
 */
import { describe, expect, it } from 'vitest';
import { REFERENCE_VALUES_PATH, loadFixturePair } from '../../tests/support/fixtures';
import { ISS_NORAD_ID, runOurPipeline } from '../../tests/support/heavensAbove';
import { hasReferenceValues, loadReferenceValues } from '../../tests/support/reference';

describe('reference-values.json', () => {
  it('exists (generated by `npx tsx scripts/validate-iss.ts --fixture 2026-09-02 --write-reference`)', () => {
    expect(hasReferenceValues(), `missing ${REFERENCE_VALUES_PATH}`).toBe(true);
  });

  if (!hasReferenceValues()) return;
  const ref = loadReferenceValues();
  const pair = loadFixturePair(ref.fixture, ref.ommFixture);

  it('names the committed fixture pair and its ISS element set', () => {
    const iss = pair.omm.find((r) => r.NORAD_CAT_ID === ISS_NORAD_ID);
    expect(iss?.EPOCH).toBe(ref.iss.epoch);
    expect(pair.ha.capturedAt).toBe(ref.capturedAt);
    expect(Date.parse(ref.capturedAt)).toBe(ref.t);
    expect(pair.ha.observer).toEqual(ref.observer);
  });

  it('reproduces the first golden pass start / peak / end', () => {
    const first = runOurPipeline(pair.ha, pair.omm)[0];
    if (!ref.firstGoldenPass) {
      expect(first).toBeUndefined();
      return;
    }
    expect(first).toBeDefined();
    if (!first) return;
    for (const key of ['start', 'peak', 'end'] as const) {
      expect(first[key].t).toBe(ref.firstGoldenPass[key].t);
      expect(first[key].azDeg).toBeCloseTo(ref.firstGoldenPass[key].azDeg, 6);
      expect(first[key].elDeg).toBeCloseTo(ref.firstGoldenPass[key].elDeg, 6);
      expect(first[key].rangeKm).toBeCloseTo(ref.firstGoldenPass[key].rangeKm, 6);
    }
    expect(first.startReason).toBe(ref.firstGoldenPass.startReason);
    expect(first.endReason).toBe(ref.firstGoldenPass.endReason);
    expect(first.peakMagnitude).toBeCloseTo(ref.firstGoldenPass.peakMagnitude, 6);
    expect(first.sunAltAtPeakDeg).toBeCloseTo(ref.firstGoldenPass.sunAltAtPeakDeg, 6);
    expect(first.twilight).toBe(ref.firstGoldenPass.twilight);
  });
});
