import { useEffect, useId, useRef } from 'react';
import { createPortal } from 'react-dom';
import { useT } from '../../../i18n/useT';
import { SHORTCUTS } from '../../../lib/shortcuts';
import styles from './ShortcutsOverlay.module.css';

/**
 * R35 (FR-DESK-4, US-14 AC4, D-73): the list `?` opens, generated by mapping
 * `SHORTCUTS` — there is no literal key in this file, so the overlay cannot
 * fall behind the table that registers the handlers, and a row without a
 * description in `t.shortcuts.does` is a `tsc -b` failure rather than a blank
 * cell.
 *
 * A modal dialog, unlike the wide guide panel (D-118): it does cover the page,
 * nothing behind it is meant to be used while it is up, and `Esc` closes it
 * first (the `close` shortcut takes the overlay before the guide). Focus moves
 * to the heading on open and back to whatever had it on close, the way the
 * compact sheet does it.
 *
 * The keys are `<kbd>` and are not translated: they are what is written on the
 * keyboard, the same in both languages (FR-I18N-4).
 */
export interface ShortcutsOverlayProps {
  onClose: () => void;
}

export function ShortcutsOverlay({ onClose }: ShortcutsOverlayProps) {
  const t = useT();
  const headingId = useId();
  const headingRef = useRef<HTMLHeadingElement>(null);
  const openerRef = useRef<Element | null>(null);

  useEffect(() => {
    openerRef.current = document.activeElement;
    headingRef.current?.focus();
    return () => {
      const opener = openerRef.current;
      if (opener instanceof HTMLElement && opener.isConnected) opener.focus();
    };
  }, []);

  return createPortal(
    <div role="dialog" aria-modal="true" aria-labelledby={headingId} className={styles.overlay} data-testid="shortcuts-overlay">
      <div className={styles.frame}>
        <div className={styles.topRow}>
          <h2 id={headingId} ref={headingRef} tabIndex={-1} className={styles.heading}>
            {t.shortcuts.title}
          </h2>
          <button type="button" className={styles.close} onClick={onClose}>
            {t.shortcuts.close}
          </button>
        </div>
        <table className={styles.table}>
          <thead>
            <tr>
              <th scope="col">{t.shortcuts.keyHeading}</th>
              <th scope="col">{t.shortcuts.doesHeading}</th>
            </tr>
          </thead>
          <tbody>
            {SHORTCUTS.map((shortcut) => (
              <tr key={shortcut.id} data-shortcut={shortcut.id}>
                <td>
                  <kbd className={styles.key}>{shortcut.label}</kbd>
                </td>
                <td>{t.shortcuts.does[shortcut.id]}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>,
    document.body,
  );
}
