import type { AppStore } from './store';

/**
 * Registering the app-shell service worker (FR-OFF-1, FR-X-4 amended, D-79).
 *
 * The worker itself is generated by the build — Workbox in `generateSW` mode
 * with `runtimeCaching: []`, so it precaches the shell and handles no data
 * request — and it imports nothing of ours (PLAN §6). This module is the only
 * thing on our side of it: it registers the file, and it turns "a new version
 * is waiting" into the store flag `UpdateBanner.tsx` reads (OQ-14).
 *
 * Registration is deliberately hand-written rather than taken from
 * `virtual:pwa-register` (D-126): the app already has a store, and the virtual
 * module's own state would be a second place where "an update is waiting"
 * lives. What it saves — about twenty lines — is less than what a lifecycle we
 * cannot unit-test costs.
 *
 * The update is never applied on our own initiative. A new worker installs and
 * waits; `applyUpdate` is the only thing that lets it through, and R28's banner
 * is its only caller, so nothing swaps under an open pass or the live page.
 */

/** Workbox's generated worker skips waiting when it is sent this, and only then. */
export const SKIP_WAITING = 'SKIP_WAITING';

/** The worker the build writes to the site root, so its scope is the whole app. */
export const SERVICE_WORKER_URL = '/sw.js';

/** The pieces of the browser this module touches, named so a test can supply them. */
export interface ServiceWorkerHost {
  container: ServiceWorkerContainer | undefined;
  reload: () => void;
}

export function browserHost(): ServiceWorkerHost {
  return {
    container: typeof navigator === 'undefined' ? undefined : navigator.serviceWorker,
    reload: () => {
      window.location.reload();
    },
  };
}

/**
 * Registers the worker and reports a waiting version to the store.
 *
 * Returns the registration, or null when there is nothing to do: no service
 * worker support (older Safari, and any browser with storage blocked), or a
 * development build, where no worker is generated and a stale precache would
 * hide every edit (`enabled` defaults to `import.meta.env.PROD`, so this is
 * the behaviour and not a convention anyone has to remember).
 *
 * A failed registration is swallowed on purpose. Offline is an enhancement
 * here: everything the app does, it does without a worker, so a browser that
 * refuses one gets the app and no error.
 */
export async function registerServiceWorker(
  store: AppStore,
  host: ServiceWorkerHost = browserHost(),
  enabled: boolean = import.meta.env.PROD,
): Promise<ServiceWorkerRegistration | null> {
  const { container } = host;
  if (!enabled || !container) return null;

  let applying = false;
  container.addEventListener('controllerchange', () => {
    // Only ours: a controller change we did not ask for is the first worker
    // taking control of this page, which must not reload it.
    if (applying) host.reload();
  });

  const offer = (worker: ServiceWorker): void => {
    store.getState().offerUpdate(() => {
      applying = true;
      worker.postMessage({ type: SKIP_WAITING });
    });
  };

  try {
    const registration = await container.register(SERVICE_WORKER_URL, { scope: '/', type: 'classic' });
    // Already waiting: the version was downloaded on an earlier visit and the
    // page was never reloaded, so there is no `updatefound` left to hear.
    if (registration.waiting && container.controller) offer(registration.waiting);
    registration.addEventListener('updatefound', () => {
      const installing = registration.installing;
      // No controller means this is the first worker of all, not an update.
      if (!installing || !container.controller) return;
      installing.addEventListener('statechange', () => {
        if (installing.state === 'installed') offer(installing);
      });
    });
    return registration;
  } catch {
    return null;
  }
}
